name: "${project.name}"
description: "${project.description}"
website: "${project.parent.url}"
authors: [ Jielos ]

main: fr.jielos.strangerhide.StrangerHideTextures
version: ${project.version}
api-version: 1.19

load: POSTWORLD

depend: [StrangerHide-API]

commands:
  models:
    permission: op
    description: "Permet de gérer les modèles disponibles."
    usage: "§cErreur de syntaxe: /<command> give/disguise/undisguise [nom du modèle] (player)"